#!/usr/bin/env bash
set -euo pipefail

# ── skill-web-ide deployment script ──────────────────────────────────
# Sets up and runs skill-web-ide on a bare machine.
# All options have sensible defaults; run with zero args to just work.
#
# Usage:
#   ./deploy.sh [OPTIONS]
#
# Options:
#   --host HOST            Listen host (default: 0.0.0.0)
#   --port PORT            Listen port (default: 3001)
#   --data-dir DIR         Root data directory (default: ~/.skill-ide)
#   --skills-dir DIR       Skills workspace directory
#   --runs-dir DIR         Run output directory
#   --sessions-dir DIR     Sessions directory
#   --repo URL             Git repo URL to clone
#   --update               Pull latest and rebuild without losing data
#   --systemd              Generate a systemd service file
#   --pm2                  Generate a pm2 ecosystem file
#   --help                 Show this help message
# ─────────────────────────────────────────────────────────────────────

REPO_URL="https://github.com/qsbao/skill-web-ide.git"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Defaults ─────────────────────────────────────────────────────────
HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-3001}"
DATA_DIR="${DATA_DIR:-$HOME/.skill-ide}"
SKILLS_DIR="${SKILLS_DIR:-}"
RUNS_DIR="${RUNS_DIR:-}"
SESSIONS_DIR="${SESSIONS_DIR:-}"
UPDATE=false
GEN_SYSTEMD=false
GEN_PM2=false

# ── Parse arguments ─────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --host)       HOST="$2"; shift 2 ;;
    --port)       PORT="$2"; shift 2 ;;
    --data-dir)   DATA_DIR="$2"; shift 2 ;;
    --skills-dir) SKILLS_DIR="$2"; shift 2 ;;
    --runs-dir)   RUNS_DIR="$2"; shift 2 ;;
    --sessions-dir) SESSIONS_DIR="$2"; shift 2 ;;
    --repo)       REPO_URL="$2"; shift 2 ;;
    --update)     UPDATE=true; shift ;;
    --systemd)    GEN_SYSTEMD=true; shift ;;
    --pm2)        GEN_PM2=true; shift ;;
    --help)
      sed -n '2,/^# ──$/{ /^#/s/^# \?//p }' "$0"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Resolve sub-directories relative to DATA_DIR if not explicitly set
SKILLS_DIR="${SKILLS_DIR:-$DATA_DIR/skills-workspace}"
RUNS_DIR="${RUNS_DIR:-$DATA_DIR/runs}"
SESSIONS_DIR="${SESSIONS_DIR:-$DATA_DIR/sessions}"

# ── Colors ───────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
else
  GREEN=''; YELLOW=''; RED=''; BOLD=''; NC=''
fi

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
die()   { error "$@"; exit 1; }

# ── 1. Pre-flight checks ────────────────────────────────────────────
info "Running pre-flight checks..."

command -v git >/dev/null 2>&1 || die "git is not installed. Please install git first."

# Check Node.js
if ! command -v node >/dev/null 2>&1; then
  die "Node.js is not installed. Please install Node.js >= 18: https://nodejs.org/"
fi
NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if [[ "$NODE_VERSION" -lt 18 ]]; then
  die "Node.js >= 18 required (found v$(node -v)). Please upgrade."
fi
info "Node.js $(node -v) OK"

# Check pnpm
if ! command -v pnpm >/dev/null 2>&1; then
  warn "pnpm not found. Attempting to enable via corepack..."
  if command -v corepack >/dev/null 2>&1; then
    corepack enable
    corepack prepare pnpm@latest --activate
    info "pnpm installed via corepack"
  else
    die "pnpm is not installed and corepack is unavailable. Install pnpm: https://pnpm.io/installation"
  fi
fi
info "pnpm $(pnpm -v) OK"

# ── 2. Clone & build ────────────────────────────────────────────────
# Determine project directory
if [[ -f "$SCRIPT_DIR/package.json" ]] && grep -q '"skill-web-ide"' "$SCRIPT_DIR/package.json" 2>/dev/null; then
  PROJECT_DIR="$SCRIPT_DIR"
  if $UPDATE; then
    info "Pulling latest changes..."
    git -C "$PROJECT_DIR" pull --rebase
  fi
else
  PROJECT_DIR="$DATA_DIR/skill-web-ide"
  if [[ -d "$PROJECT_DIR/.git" ]]; then
    if $UPDATE; then
      info "Pulling latest changes..."
      git -C "$PROJECT_DIR" pull --rebase
    else
      info "Repository already cloned at $PROJECT_DIR"
    fi
  else
    info "Cloning repository..."
    mkdir -p "$(dirname "$PROJECT_DIR")"
    git clone "$REPO_URL" "$PROJECT_DIR"
  fi
fi

info "Installing dependencies..."
cd "$PROJECT_DIR"
pnpm install --frozen-lockfile 2>/dev/null || pnpm install

info "Building project..."
pnpm build

# ── 3. Generate .env ────────────────────────────────────────────────
ENV_FILE="$PROJECT_DIR/.env"
info "Writing $ENV_FILE"
cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
HOST=$HOST
PORT=$PORT
SKILLS_DIR=$SKILLS_DIR
RUNS_DIR=$RUNS_DIR
SESSIONS_DIR=$SESSIONS_DIR
EOF

# ── 4. Init directories ─────────────────────────────────────────────
info "Ensuring data directories exist..."
mkdir -p "$SKILLS_DIR" "$RUNS_DIR" "$SESSIONS_DIR"

# ── 5. Generate service files (optional) ─────────────────────────────
if $GEN_SYSTEMD; then
  SERVICE_FILE="$DATA_DIR/skill-web-ide.service"
  info "Generating systemd service file: $SERVICE_FILE"
  cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Skill Web IDE
After=network.target

[Service]
Type=simple
WorkingDirectory=$PROJECT_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$(command -v node) $PROJECT_DIR/backend/dist/index.js
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  info "To install: sudo cp $SERVICE_FILE /etc/systemd/system/ && sudo systemctl enable --now skill-web-ide"
fi

if $GEN_PM2; then
  PM2_FILE="$DATA_DIR/ecosystem.config.cjs"
  info "Generating pm2 config: $PM2_FILE"
  cat > "$PM2_FILE" <<EOF
module.exports = {
  apps: [{
    name: 'skill-web-ide',
    cwd: '$PROJECT_DIR',
    script: 'backend/dist/index.js',
    env: {
      HOST: '$HOST',
      PORT: '$PORT',
      SKILLS_DIR: '$SKILLS_DIR',
      RUNS_DIR: '$RUNS_DIR',
      SESSIONS_DIR: '$SESSIONS_DIR',
    },
  }],
};
EOF
  info "To start: pm2 start $PM2_FILE"
fi

# ── 6. Summary ───────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo -e "${BOLD} skill-web-ide — deployment complete${NC}"
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Project dir:    ${GREEN}$PROJECT_DIR${NC}"
echo -e "  Data dir:       ${GREEN}$DATA_DIR${NC}"
echo -e "  Skills dir:     ${GREEN}$SKILLS_DIR${NC}"
echo -e "  Runs dir:       ${GREEN}$RUNS_DIR${NC}"
echo -e "  Sessions dir:   ${GREEN}$SESSIONS_DIR${NC}"
echo ""
echo -e "  Host:           ${GREEN}$HOST${NC}"
echo -e "  Port:           ${GREEN}$PORT${NC}"
echo -e "  Access URL:     ${GREEN}http://$HOST:$PORT${NC}"
echo ""
echo -e "  Start command:  ${YELLOW}cd $PROJECT_DIR && node backend/dist/index.js${NC}"
echo ""
